### ISSUE TITLE
Wallpaper use lots of ram

### ISSUE THREAD

**Issue by eoli3n** [swaywm/swaybg#19] opened 2020-11-14 12:20 UTC
Hi, 

I use a big screen layout with sway:
- https://github.com/eoli3n/dotfiles/blob/master/roles/sway/templates/by_host/osz/config.j2#L9

I use variety to set my background: 
- https://github.com/varietywalls/variety
- https://github.com/eoli3n/dotfiles/blob/master/roles/sway/templates/by_host/osz/config.j2#L47

I noticed today that ``swaybg`` is using a lots of RAM:
![2020-11-14T13:16:37,722896952+01:00](https://user-images.githubusercontent.com/14223657/99146811-ad952e00-267b-11eb-8b1e-9829aa2a9eb9.png)
```
➜ ps aux | grep swaybg
user     1512217  0.0  9.0 736848 721596 tty1    S+   11:38   0:02 swaybg -o DP-5 -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill -o DP-6 -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill -o eDP-1 -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill -o * -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill -o DP-2 -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill -o DP-3 -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg -m fill
```
```
➜ swaymsg -t get_outputs
Output DP-2 'ONKYO Corporation Sound System 0x00000000'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 3291,307
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 72.808998 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 72.188004 Hz
    800x600 @ 75.000000 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 70.069000 Hz
    1024x768 @ 75.028999 Hz
    1024x768 @ 119.988998 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x800 @ 59.910000 Hz
    1280x800 @ 119.908997 Hz
    1440x900 @ 59.901001 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x1200 @ 60.000000 Hz
    1920x1080 @ 23.976000 Hz
    1920x1080 @ 24.000000 Hz
    1920x1080 @ 25.000000 Hz
    1920x1080 @ 29.969999 Hz
    1920x1080 @ 30.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output DP-3 'Dell Inc. DELL P2417H CW6Y77AG05NB' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 3291,1387
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2:
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 75.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 75.000000 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 75.028999 Hz
    1152x864 @ 75.000000 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output eDP-1 'Chimei Innolux Corporation 0x14D3 0x00000000'
  Current mode: 1920x1080 @ 60.007999 Hz
  Position: 5211,1694
  Scale factor: 1.400000
  Scale filter: linear
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3:
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.007999 Hz
```
I can see that variety run a command even of non existent monitors, i will open an issue there. But is the ram consumption related to this ?

**Comment by eoli3n** [comment] 2020-11-14 12:32
Killing swaybg then rerun manually 
```
swaybg -o '*' -m fill -i /home/user/.config/variety/Downloaded/Unsplash/photo-1504575797-2f83688754b8.jpg
```
![2020-11-14T13:29:49,848938008+01:00](https://user-images.githubusercontent.com/14223657/99147012-8d666e80-267d-11eb-8de0-7acb3a77b44e.png)

Maybe sway bg should test config:
- if there is ``'*'``, then ignore all other configs
else
- test if output exists, then print bg

**Comment by emersion** [comment] 2021-06-24 09:52
Duplicate of https://github.com/swaywm/swaybg/issues/14

**Closed by emersion** 2021-06-24 09:52 UTC
