### ISSUE TITLE
sway -C ; [main.c:521] Missing a required Wayland interface

### ISSUE THREAD

**Issue by mh4nx7net** [swaywm/swaybg#12] opened 2020-01-06 11:26 UTC
` [main.c:521] Missing a required Wayland interface`
so sory for opening the issue rapidly
just getting litle red log message of sway with checking by param [-C] (validation of config file)
chop of my conf is like
`output * bg $image_url/img.jpg fill`

is myconf fine in format typing, coz when iam remove them. it goes fine no any _redlove_msg, or there some issues with swaybg or maybe swaywm itself ?
this is what iam used
`sway version 1.2-897c36b1 (Jan  6 2020, branch 'master')`
`swaybg version 1.0-2-ga8f109a (Jan  3 2020, branch 'master')`

is it fine ? maybe there somebody else who have some little _redlove_ message like me

**Comment by ejez** [comment] 2020-04-28 14:58
Having the same issue. As soon as I add a background in `.config/sway/config`:
```sh
output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
```
I get the following when I run `sway -C`
```sh
[swaybg-1.0/main.c:521] Missing a required Wayland interface
```

**Comment by toazd** [comment] 2020-05-12 13:07
I'm not sure if this is related or not but maybe this can help either of you further diagnose or solve your issues.

I get this exact error but only under the following conditions:
I have a second monitor definition that is after the background image definition in the config:
```
output * bg /storage/Pictures/johannes-plenio-RwHv7LgeC7s-unsplash.jpg fill
output HDMI-A-1 resolution 1920x1080 position 1920,0
output HDMI-A-2 resolution 1440x900 position 3840,0
```

With the config like this, if I unplug the second monitor and reload the sway configuration or startup sway without the second monitor plugged in this error appears in my sway.log (I startup sway via .bash_profile and redirect the output to a log file: exec sway &>> ${HOME}/sway.log).

If I move my background definition to after the monitor definitions as such:
```
output HDMI-A-1 resolution 1920x1080 position 1920,0
output HDMI-A-2 resolution 1440x900 position 3840,0
output * bg /storage/Pictures/johannes-plenio-RwHv7LgeC7s-unsplash.jpg fill
```
The error no longer appears in my log when the second monitor is not plugged in and I reload the configuration or startup sway without the second monitor plugged in.

**Comment by manio** [comment] 2020-09-18 15:35
Hello guys,
Is there some fix or workaround for this problem? I just updated my debian box (for several months) and updated a sway:
```sway:amd64 (1.4-2, 1.5-3)```
And the sway stopped starting: :(
```[main.c:521] Missing a required Wayland interface```

I have a multimonitor setup.
I was also trying to disable the ```output * bg``` line in the config but it doesn't help...
Full log: http://skyboo.net/temp/sway/sway_not_working.log

The worst thing is that when I downgraded the package from 1.5-3 to 1.4-2 it is still not working :(
Any tips - what package could also cause this problem?

**Comment by manio** [comment] 2020-09-21 06:17
Update:
I decided to uninstall debian wlroots and sway packages and installed it from source (newest master).
I also compiled swaybg.
The result is the same ("Missing a required Wayland interface) and additionaly sway is crashing.
Full log: http://skyboo.net/temp/sway/sway-bt-full.log

**Comment by manio** [comment] 2020-09-21 11:46
Thanks to @kennylevinsen tips I discovered that the problem is related with kernel version. I tested the following debian kernels:
5.8.0-2-amd64 - crashing
5.8.0-1-amd64 - crashing
5.6.0-2-amd64 - working

swaybg is probably not related

**Comment by manio** [comment] 2020-09-22 02:37
Oh and some comment regarding this specific "issue" in the swaybg:
Yesterday when I was diagnosing sway crashing problem, I've put additional debug to test why the "Missing a required Wayland interface" error is showing in the swaybg...
The result was that all 4 if statements components was null (state.compositor, state.shm, state.layer_shell and state.xdg_output_manager), in: https://github.com/swaywm/swaybg/blob/master/main.c#L519
And this has to be just right after the sway has crashed...
dunno ... maybe this error is a little misleading to end user in such cases (in fact the previous one about "Unable to connect to the compositor" would be more proper i think... I leave it to you guys...

**Comment by emersion** [comment] 2021-07-19 09:45
Closing because this doesn't look like a swaybg bug.

**Closed by emersion** 2021-07-19 09:45 UTC
