### ISSUE TITLE
swaybg: Failed to load background image

### ISSUE THREAD

**Issue by sweetyoru** [swaywm/swaybg#82] opened 2024-12-23 00:07 UTC
After an upgrade, swaybg failed to set background.

1. Command to run: `swaybg -i a.png -m fill`
2. Error message:
```
2024-12-23 07:06:19 - [main.c:282] Found config * for output eDP-1 ((null) (null))
2024-12-23 07:06:19 - [background-image.c:30] Failed to load background image (Couldn’t recognize the image file format for file “a.png”).
2024-12-23 07:06:19 - [main.c:610] Failed to load image: a.png
2024-12-23 07:06:19 - [background-image.c:30] Failed to load background image (Couldn’t recognize the image file format for file “a.png”).
2024-12-23 07:06:19 - [main.c:610] Failed to load image: a.png
```
3. swaybg version: `swaybg version 1.2.1`
4. sway version: `sway version 1.9`

**Comment by mstoeckl** [comment] 2024-12-23 00:23
The error suggests that the image file may not actually be a PNG file, and just has `.png` as its extension. What is the result of `file a.png`?

This could also be an issue with GdkPixbuf, the library that `swaybg` uses to load images. The error message comes from: https://github.com/swaywm/swaybg/blob/d7ec784e5d69af9d9addf5ef95df5c40af3df478/background-image.c#L28-L30

**Comment by sweetyoru** [comment] 2024-12-23 00:25
The image is indeed a png file, as it works perfectly fine before the system upgrade. It also open in feh.

```
  ➜ file a.png
a.png: PNG image data, 1300 x 919, 8-bit/color RGB, non-interlaced
```

**Comment by mstoeckl** [comment] 2024-12-23 00:40
The relevant code in swaybg hasn't changed in a long time. This most likely is a GdkPixbuf library issue or something with your system (e.g. broken GdkPixbuf loader cache files, or (possibly?) mime type cache).

One way to test whether this is the case (which admittedly can have false positives/negatives) is to check a different program that uses GdkPixbuf. For example, does `gdk-pixbuf-thumbnailer a.png output.png` successfully produce a smaller image?

**Comment by sweetyoru** [comment] 2024-12-23 00:45
`gdk-pixbuf-thumbnailer a.png output.png` failed with error `Could not thumbnail 'a.png': Couldn’t recognize the image file format for file`.

It's likely to be a GdkPixbuf bug as you suggested.

**Comment by mstoeckl** [comment] 2024-12-23 00:55
Closing issue, as very unlikely to be caused by swaybg. I'd recommend trying to reinstall gdk-pixbuf or any other upgraded packages in case the upgrade was corrupted/partially failed, and if that doesn't help use distribution-specific help channels or file an issue with [GdkPixbuf](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues).

(And thank you for your prompt and clear replies!)

**Closed by mstoeckl** 2024-12-23 00:55 UTC
