### ISSUE TITLE
Feature request: randomization

### ISSUE THREAD

**Issue by cassio-tav** [swaywm/swaybg#16] opened 2020-08-23 21:33 UTC
### Feature
The ability to chose randomly a background image from a directory or directory tree.

### The problem and its context
I have a small local network with a few users and machines. In a shared file-system
there is a `wallpapers` directory-tree, where images are organized by categories
and subcategories (it's not a very large tree). Each user has then the
possibility to set her/his screen's background with `feh`, to display either
1. a given image from the shared wallpapers directory-tree (or any image of his/her
    own);
1. a random image from the whole wallpapers' directory-tree (or from any branch of
    that tree, or actually from any directory or directory-tree).

Now that we have decided to transition from X11 to Wayland and so we have also
moved from i3 to Sway. But given that Sway comes with its own background image
setter, we hoped not to need a replacement for `feh`...

### Suggested usage syntax
1. To pass the wallpaper directory, either:
    * allow the path given to the `-i` option to be a directory and decide automatically 
      what to do based on the file-type, or 
    * add a new option (perhaps `-d`) for that specific purpose. 
1. Add an extra option to recurse the directory-tree (perhaps -r).

**Comment by emersion** [comment] 2020-08-23 21:39
Duplicate of https://github.com/swaywm/swaybg/issues/11

**Closed by emersion** 2020-08-23 21:39 UTC
