### ISSUE TITLE
When setting a wallpaper image, the background switches to gray and then to the image

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/swaybg#3] opened 2019-04-29 13:54 UTC
I'm moving this from the sway repository to here (since I have the same problem and am writing a program like blurwal). This issue was originally created by @xyproto. Here's what he said originally:

Hi,

I wrote a utility for being able to set Timed Wallpapers (wallpaper slideshows, with crossfade between images) that also works for Wayland/Sway.

This works nicely, but when the wallpaper is changed, the background blinks by first switching to gray and then to the selected image.

Steps to reproduce:

Install the [Mojave timed wallpaper](https://github.com/japamax/gnome-mojave-timed-wallpaper), either from GitHub or from the AUR package named `gnome-mojave-timed-wallpaper` (if you use Arch Linux).
Install [wallutils](https://github.com/xyproto/wallutils), either from GitHub or from the AUR package named `wallutils` (if you use Arch Linux).
Run this command `settimed mojave-timed`.
Then just wait a bit, and the background will blink every few minutes.

The command being run for setting the wallpaper looks like this:

```
swaymsg 'output "*" background /usr/share/backgrounds/gnome/mojave/mojave_dynamic-1320.jpg fill'
```

This is a feature request for the background image to be switched smoothly, without the background blinking.

I'm using `sway version 1.0-beta.1-245-gdbf8e1ce (Nov 27 2018, branch 'master')` and have also tested with the latest master of sway (which fixes the problem with the windows blinking too).

Thanks for creating Sway!

**Comment by emersion** [comment] 2019-04-29 14:57
Duplicate of https://github.com/swaywm/sway/issues/3693

**Closed by emersion** 2019-04-29 14:57 UTC
