### ISSUE TITLE
bash-completion doesn't obey prefix

### ISSUE THREAD

**Issue by jhidding** [swaywm/swaybg#13] opened 2020-03-15 12:30 UTC
## casus
Trying to install as a user with `meson configure --prefix ${HOME}/.local`. 

## behaviour
Bash-completion files are still installed in system-wide folder, failing without root privilege.

## desired behaviour
Bash-completion files should end up in: $HOME/.local/share/bash-completion/completions or similar.

I'm unfamiliar with Meson internals, so I don't know how

```
bash_comp      = dependency('bash-completion', required: false)
```

and

```
bash_install_dir = bash_comp.get_pkgconfig_variable('completionsdir')
```

are resolved.

Otherwise I would be happy to create a PR.

**Comment by emersion** [comment] 2020-03-15 15:59
I think the issue is that bash doesn't use the `prefix` variable in its pkg-config file:

```
prefix=/usr
datadir=/usr/share
sysconfdir=/etc

compatdir=${sysconfdir}/bash_completion.d
completionsdir=${datadir}/bash-completion/completions
helpersdir=${datadir}/bash-completion/helpers
```

`datadir` is defined straight up, should probably be `datadir=${prefix}/share`.

Can you try `meson configure --prefix ${HOME}/.local --datadir ${HOME}/.local/share`?

**Comment by martinetd** [comment] 2020-03-29 12:02
> Can you try meson configure --prefix ${HOME}/.local --datadir ${HOME}/.local/share?

FWIW that doesn't work, `meson configure` will output it back as `share` (e.g. it will automatically strips down path prefix) ; either way the value within meson of datadir is correct.

... Actually on my system bash-completion uses `${prefix}`
```
$ cat /usr/share/pkgconfig/bash-completion.pc
prefix=/usr
compatdir=/etc/bash_completion.d
completionsdir=${prefix}/share/bash-completion/completions
helpersdir=${prefix}/share/bash-completion/helpers

Name: bash-completion
Description: programmable completion for the bash shell
URL: https://github.com/scop/bash-completion
Version: 2.8
```

So the problem is that they overwrite prefix? But it seems obvious they would have to; it has to point to where bash-completion completions are installed...

I actually just don't think pkgconfig is the right tool for us here, I don't see how it could be used in a way that works for us.

**Comment by emersion** [comment] 2020-03-29 13:56
From the `get_pkgconfig_variable` Meson docs:

> (Added 0.44.0) You can also redefine a variable by passing a list to the define_variable parameter that can affect the retrieved variable: ['prefix', '/'])

We could just do that?

**Comment by emersion** [comment] 2020-03-29 14:01
Or maybe we should just give up and hardcode the completionsdir path as you said, I don't know.

**Comment by martinetd** [comment] 2020-03-29 14:07
Oh, nice one; this appears to work (weird syntax though):
```
bash_install_dir = bash_comp.get_pkgconfig_variable('completionsdir',
                                  define_variable: ['prefix', prefix])
```

fish completion hardcodes /usr/local though so until your PR there moves we can't do much about it. I'll let you/others decide on this.

**Comment by emersion** [comment] 2020-03-30 12:41
Refs:

* https://github.com/mesonbuild/meson/issues/6873
* https://github.com/mesonbuild/meson/issues/6874

**Comment by emersion** [comment] 2020-04-04 12:18
The [fish pull request[(https://github.com/fish-shell/fish-shell/pull/6778) has been merged.

**Comment by martinetd** [comment] 2020-04-04 13:19
Great, I'm now confused about this issue because swaybg does not seem to have any completion, but will submit a patch to sway using that.

**Closed** 2020-04-04 15:55 UTC
